# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iAquarium2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iAquarium2
  pod 'Eureka'
  pod 'ImageRow', '~> 4.0'
  target 'iAquarium2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iAquarium2UITests' do
    # Pods for testing
  end

end
